# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `elm-rails` gem.
# Please instead update this file by running `bin/tapioca gem elm-rails`.

# source://elm-rails//lib/elm/rails/helper.rb#1
module Elm; end

# source://elm-rails//lib/elm/rails/helper.rb#2
module Elm::Rails; end

# source://elm-rails//lib/elm/rails/helper.rb#3
module Elm::Rails::Helper
  # source://elm-rails//lib/elm/rails/helper.rb#4
  def elm_embed(module_name, args = T.unsafe(nil)); end

  private

  # source://elm-rails//lib/elm/rails/helper.rb#12
  def component_div; end

  # source://elm-rails//lib/elm/rails/helper.rb#16
  def script_tag(module_name, args); end
end

# source://elm-rails//lib/elm/rails/railtie.rb#6
class Elm::Rails::Railtie < ::Rails::Railtie; end

# source://elm-rails//lib/elm/rails/sprockets.rb#5
class Elm::Rails::Sprockets
  # source://elm-rails//lib/elm/rails/sprockets.rb#22
  def initialize(options = T.unsafe(nil)); end

  # source://elm-rails//lib/elm/rails/sprockets.rb#20
  def cache_key; end

  # source://elm-rails//lib/elm/rails/sprockets.rb#26
  def call(input); end

  private

  # source://elm-rails//lib/elm/rails/sprockets.rb#37
  def debug_flag; end

  class << self
    # source://elm-rails//lib/elm/rails/sprockets.rb#16
    def cache_key; end

    # source://elm-rails//lib/elm/rails/sprockets.rb#12
    def call(input); end

    # source://elm-rails//lib/elm/rails/sprockets.rb#8
    def instance; end
  end
end

# source://elm-rails//lib/elm/rails/sprockets.rb#46
class Elm::Rails::Sprockets::DependencyGraph < ::Struct
  # source://elm-rails//lib/elm/rails/sprockets.rb#47
  def each(&block); end

  private

  # source://elm-rails//lib/elm/rails/sprockets.rb#67
  def import_regex; end

  # source://elm-rails//lib/elm/rails/sprockets.rb#53
  def recurse(source, block); end
end

# source://elm-rails//lib/elm/rails/sprockets.rb#6
Elm::Rails::Sprockets::VERSION = T.let(T.unsafe(nil), String)
