# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `jass-rollup` gem.
# Please instead update this file by running `bin/tapioca gem jass-rollup`.

# source://jass-rollup//lib/jass/rollup/version.rb#1
module Jass; end

# source://jass-rollup//lib/jass/rollup/version.rb#2
module Jass::Rollup; end

# source://jass-rollup//lib/jass/rollup/compiler.rb#1
class Jass::Rollup::Compiler < ::Nodo::Core
  # source://nodo/1.6.4/lib/nodo/core.rb#119
  def bundle(*args); end

  # source://nodo/1.6.4/lib/nodo/core.rb#119
  def bundle_entry(*args); end

  # source://nodo/1.6.4/lib/nodo/core.rb#119
  def bundle_esm(*args); end

  # source://jass-rollup//lib/jass/rollup/compiler.rb#11
  def compile(config); end

  # source://jass-rollup//lib/jass/rollup/compiler.rb#21
  def compile_entry(entry); end

  # source://jass-rollup//lib/jass/rollup/compiler.rb#16
  def compile_esm(mod); end

  # source://nodo/1.6.4/lib/nodo/core.rb#119
  def default_plugins(*args); end

  class << self
    # source://forwardable/1.3.2/forwardable.rb#229
    def compile(*args, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def compile_entry(*args, &block); end

    # source://forwardable/1.3.2/forwardable.rb#229
    def compile_esm(*args, &block); end
  end
end

# source://jass-rollup//lib/jass/rollup/directive_processor.rb#3
class Jass::Rollup::DirectiveProcessor
  # source://jass-rollup//lib/jass/rollup/directive_processor.rb#16
  def call(input); end

  # source://jass-rollup//lib/jass/rollup/directive_processor.rb#25
  def process_matching_directive(name, args); end

  # source://jass-rollup//lib/jass/rollup/directive_processor.rb#40
  def process_require_npm_directive(path, *args); end

  # source://jass-rollup//lib/jass/rollup/directive_processor.rb#36
  def process_rollup_directive(entry, *args); end

  # source://jass-rollup//lib/jass/rollup/directive_processor.rb#32
  def process_rollup_esm_directive(mod); end

  class << self
    # source://jass-rollup//lib/jass/rollup/directive_processor.rb#11
    def call(input); end

    # source://jass-rollup//lib/jass/rollup/directive_processor.rb#7
    def instance; end
  end
end

# source://jass-rollup//lib/jass/rollup/directive_processor.rb#4
Jass::Rollup::DirectiveProcessor::DIRECTIVES = T.let(T.unsafe(nil), Array)

# source://jass-rollup//lib/jass/rollup/processor.rb#1
module Jass::Rollup::Processor
  class << self
    # source://jass-rollup//lib/jass/rollup/processor.rb#6
    def cache_key; end

    # source://jass-rollup//lib/jass/rollup/processor.rb#10
    def call(input); end
  end
end

# source://jass-rollup//lib/jass/rollup/processor.rb#2
Jass::Rollup::Processor::VERSION = T.let(T.unsafe(nil), String)

# source://jass-rollup//lib/jass/rollup/version.rb#3
Jass::Rollup::VERSION = T.let(T.unsafe(nil), String)
