# DO NOT EDIT MANUALLY
# This is an autogenerated file for unresolved constants.
# Please instead update this file by running `bin/tapioca todo`.

# typed: false

module ::Spoom::Context; end
module ::Spoom::ExecResult; end
module ::Spoom::Sorbet::Config; end
module ::Spoom::Sorbet::Errors::Error; end
